export const ADD_COMMENT = 'ADD_COMMENT';
export const UP_VOTE_COMMENT = 'UP_VOTE_COMMENT';
export const DOWN_VOTE_COMMENT= 'DOWN_VOTE_COMMENT';
export const DELETE_COMMENT_BY_PARENT = 'DELETE_COMMENT_BY_PARENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
