export const ADD_POST = 'ADD_POST'
export const UP_VOTE_COUNT = 'UP_VOTE_COUNT'
export const DOWN_VOTE_COUNT= 'DOWN_VOTE_COUNT'
export const DELETE_POST = 'DELETE_POST'
export const EDIT_POST = 'EDIT_POST'
export const COMMENT_COUNTER = 'COMMENT_COUNTER'
export const GET_POSTS_BY_CATEGORY = 'GET_POSTS_BY_CATEGORY';
export const GET_ALL_POSTS = 'GET_ALL_POSTS';
